#!/bin/bash

standard_kernel_output_file="cscope.files"

find . -maxdepth 1 -type f > "$standard_kernel_output_file"
find arch/arm64 -type f >> "$standard_kernel_output_file"
find include -type f >> "$standard_kernel_output_file"
find kernel -type f >> "$standard_kernel_output_file"
find mm -type f >> "$standard_kernel_output_file"
find fs -type f >> "$standard_kernel_output_file"
find drivers -type f >> "$standard_kernel_output_file"
find net -type f >> "$standard_kernel_output_file"
find ipc -type f >> "$standard_kernel_output_file"
find lib -type f >> "$standard_kernel_output_file"
find security -type f >> "$standard_kernel_output_file"
find crypto -type f >> "$standard_kernel_output_file"
find sound -type f >> "$standard_kernel_output_file"
find usr -type f >> "$standard_kernel_output_file"
find block -type f >> "$standard_kernel_output_file"

echo "gen $standard_kernel_output_file"
