#!/bin/bash

output_file="cscope.files"

function find_dir
{
	find $1 -type f -name '*.c' -o -name '*.h' -o -name '*.pl' -o -name '*.sh' -o -name '*.s' -o -name '*.S' >> $output_file
}

echo "" > $output_file

find_dir arch/arm64
find_dir include
find_dir kernel
find_dir mm
find_dir fs
find_dir drivers/dma-buf
# find_dir net
find_dir ipc
find_dir lib
find_dir security
find_dir crypto
# find_dir sound
find_dir usr
find_dir block

echo "gen $output_file `wc -l $output_file`"
